language: python

python:
  - "2.7"
  # - "pypy" Not all tests are working yet

env:
  - TEST_TARGET=master
  - TEST_TARGET=slave
  - TEST_TARGET=javascript

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libsasl2-dev libmysqlclient-dev libldap2-dev libssl-dev python-dev
  - if [ $TEST_TARGET = javascript]; then npm install -g grunt-cli; fi

install:
  - pip install -e $TEST_TARGET
  - pip install -v mock==1.0.1
  - pip install -v pyflakes
  - pip install -v coveralls
  - if [ "$TEST_TARGET" = "javascript" ]; then cd www/; fi
  - if [ "$TEST_TARGET" = "javascript" ]; then npm install; fi

script:
  - if [ "$TEST_TARGET" = "master" ]; then coverage run `which trial` buildbot; fi
  - if [ "$TEST_TARGET" = "slave" ]; then coverage run `which trial` buildslave; fi
  - if [ "$TEST_TARGET" = "javascript" ]; then grunt test --verbose --force; fi

after_success:
  - coveralls